---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments-api
spec:
  destination:
    name: payments-api
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments-queue
spec:
  destination:
    name: payments-queue
  sources:
    - name: payments-api
      action: allow
