version: "2"
containers:
- name: consul-server-0
  image: consul
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  memory: 128
- name: consul-server-1
  image: consul
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  memory: 128
- name: consul-server-2
  image: consul
  ports:
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600
  memory: 128
- name: app
  image: wordpress
  ports:
  - 80
  - 443
  memory: 128
- name: database
  image: mysql
  ports:
  - 3306
  memory: 128