---
apiVersion: v1
kind: Service
metadata:
  name: payments-api
spec:
  selector:
    app: payments-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-api
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-properties-conf
data:
  application.properties: |
    app.storage=disabled
    app.encryption.enabled=false
    opentracing.jaeger.http-sender.url=http://jaeger-collector:14268/api/traces
    opentracing.jaeger.include-jaeger-env-tags=true
    logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
    opentracing.jaeger.enable-b3-propagation=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: payments-api
      app: payments-api
  template:
    metadata:
      labels:
        service: payments-api
        app: payments-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9901"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: v1
        consul.hashicorp.com/service-tags: v1
    spec:
      serviceAccountName: payments-api
      volumes:
        - name: properties-conf
          configMap:
            name: payments-properties-conf
      containers:
        - name: payments-api
          image: hashicorpdemoapp/payments:latest
          volumeMounts:
            - name: properties-conf
              mountPath: /config/application.properties
              subPath: application.properties
          ports:
            - containerPort: 8080
          env:
            - name: BIND_ADDRESS
              value: ":8080"
            - name : JAEGER_ENDPOINT
              value: http://jaeger-collector:14268/api/traces
