version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.14.1
jobs:
  license-cloud-client:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f3:bb:57:7d:be:ea:de:d0:57:e2:d7:1e:5e:b8:36:d1"
      - run: git clone git@github.com:hashicorp/instruqt-packer.git
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: instruqt-packer/consul-cloud-client
          path: instruqt-packer/consul-cloud-client
          image: consul-cloud-client
          extra_build_args: --build-arg HC_VAULT_LICENSE=$HC_VAULT_LICENSE --build-arg HC_CONSUL_LICENSE=$HC_CONSUL_LICENSE --build-arg PACKER_VERSION=$PACKER_VERSION --build-arg TF_VERSION=$TF_VERSION --build-arg VAULT_VERSION=$VAULT_VERSION --build-arg NOMAD_VERSION=$NOMAD_VERSION --build-arg CONSUL_VERSION=$CONSUL_VERSION
          tag: $CONSUL_TAG
      - gcp-gcr/push-image:
          image: consul-cloud-client
          tag: $CONSUL_TAG
    environment:
      PACKER_VERSION: 1.7.0
      TF_VERSION: 0.13.5
      VAULT_VERSION: 1.8.0+ent
      NOMAD_VERSION: 1.0.4+ent
      CONSUL_VERSION: 1.10.2+ent
      CONSUL_TAG: v1.10.2
  consul-basics:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Consul Basics
          command: |
            cd instruqt-tracks/consul-basics
            echo "Copying track files..."
            docker create -v /track --name track alpine:3.4 /bin/true
            docker cp . track:/track/
            echo "Running instruqt track validate..."
            docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --volumes-from track instruqt/cli track validate
            echo "Running instruqt track push..."
            docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --mount type=bind,source="$(pwd)",target=/track instruqt/cli track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]; do
              docker run -e INSTRUQT_TOKEN=$INSTRUQT_TOKEN --workdir="/track" --mount type=bind,source="$(pwd)",target=/track instruqt/cli track test --skip-fail-check  && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  service-discovery-with-consul:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Service Discovery with Consul
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/service-discovery-with-consul
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]; do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  service-mesh-with-consul:
    docker:
      - image: docker.mirror.hashicorp.services/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Service Mesh with Consul
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/service-mesh-with-consul
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]; do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  multi-cloud-consul:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Multi-cloud Consul
          no_output_timeout: 60m
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/multi-cloud-service-networking-with-consul
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]; do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  network-infrastructure-automation:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Network Infrastructure Automation
          no_output_timeout: 60m
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/network-infrastructure-automation
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]; do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
  life-of-a-developer:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Life of a Developer
          command: |
            VERSION=$INSTRUQT_VERSION
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            echo "yes" | instruqt version
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Instruqt is not installed correctly."
              exit 1
            else
              echo "Instruqt is installed and updated to most recent version."
            fi
            cd /root/project/instruqt-tracks/consul-life-of-a-developer
            echo "Running instruqt track push..."
            instruqt track push --force
            echo "Running instruqt track test..."
            # Retry instruqt track test up to 3 times
            n=0
            until [ $n -ge 3 ]; do
              instruqt track test --skip-fail-check && break
              n=$[$n+1]
              sleep 60
            done
            if [ $n -ge 3 ]; then
              echo "Instruqt track test failed three times."
              exit 1
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - license-cloud-client:
          filters:
            branches:
              only:
                - master
      - consul-basics
      - service-discovery-with-consul:
          filters:
            branches:
              only:
                - master
      - service-mesh-with-consul:
          filters:
            branches:
              only:
                - master
      - network-infrastructure-automation:
          filters:
            branches:
              only:
                - master
      - life-of-a-developer:
          filters:
            branches:
              only:
                - master
      - multi-cloud-consul:
          requires:
            - license-cloud-client
          filters:
            branches:
              only:
                - master
  nightly-build:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - license-cloud-client
      - consul-basics
      - service-discovery-with-consul
      - service-mesh-with-consul
      - network-infrastructure-automation
      - life-of-a-developer
      - multi-cloud-consul:
          requires:
            - license-cloud-client
