version: 2
jobs:
  install-instruqt:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install Instruqt
          command: |
            VERSION=1270-4cde42d
            apt -y update
            apt -y install wget unzip
            wget https://github.com/instruqt/cli/releases/download/${VERSION}/instruqt-linux-${VERSION}.zip -O /tmp/instruqt.zip
            cd /tmp
            unzip instruqt.zip
            cp instruqt /usr/local/bin/instruqt
            chmod +x /usr/local/bin/instruqt
            instruqt version | grep $VERSION
            RETVAL=$?
            if [[ $RETVAL -ne 0 ]]; then
              echo "Version $VERSION is not installed correctly."
              exit 1
            else
              echo "Instruqt Version $VERSION is installed."
              exit 0
            fi
            cd ~/instruqt-tracks/consul-basics && instruqt track validate
            cd ~/instruqt-tracks/consul-service-discovery2 && instruqt track validate
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-instruqt