---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-cache
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payment-cache
spec:
  protocol: tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-cache
  labels:
    app: payment-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-cache
  template:
    metadata:
      labels:
        app: payment-cache
    spec:
      serviceAccountName: payment-cache
      containers:
      - name: redis
        image: "redis:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
