---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-queue
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments-queue
spec:
  protocol: tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-queue
  labels:
    app: payments-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-queue
  template:
    metadata:
      labels:
        app: payments-queue
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: payments-queue
      containers:
      - name: payments-queue
        image: "redis:latest"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
