---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  labels:
    app: app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-protocol": "grpc"
        "consul.hashicorp.com/connect-service-upstreams": "app-cache:9092,app-payments:9093"
    spec:
      containers:
      - name: app-api
        image: "nicholasjackson/fake-service:v0.5.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9091"
          - name: UPSTREAM_URIS
            value: "http://127.0.0.1:9092, http://127.0.0.1:9093"
          - name: MESSAGE
            value: "API response"
          - name: NAME
            value: "api"
          - name: SERVER_TYPE
            value: "grpc"
          - name: TIMING_50_PERCENTILE
            value: "20ms"
          - name: TIMING_90_PERCENTILE
            value: "30ms"
          - name: TIMING_90_PERCENTILE
            value: "40ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector:9411"
