---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend
spec:
  type: NodePort
  selector:
    app: app-frontend
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  labels:
    app: app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "app-api:9091"
    spec:
      containers:
      - name: app-frontend
        image: "nicholasjackson/fake-service:v0.5.2"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9090"
          - name: UPSTREAM_URIS
            value: "grpc://127.0.0.1:9091"
          - name: MESSAGE
            value: "Hello World"
          - name: NAME
            value: "web"
          - name: SERVER_TYPE
            value: "http"
          - name: TIMING_50_PERCENTILE
            value: "30ms"
          - name: TIMING_90_PERCENTILE
            value: "60ms"
          - name: TIMING_90_PERCENTILE
            value: "90ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger-collector:9411"
