---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod-customer
  labels:
    app: hotrod-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod-customer
  template:
    metadata:
      labels:
        app: hotrod-customer
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: hotrod-customer
        image: "jaegertracing/example-hotrod:latest"
        imagePullPolicy: Always
        command: ["/go/bin/hotrod-linux"]
        args: ["customer"]
        ports:
        - containerPort: 8081
        env:
          - name: JAEGER_AGENT_HOST
            value: "jaeger-agent"
          - name: JAEGER_AGENT_PORT
            value: "6831"
