---
apiVersion: v1
kind: Service
metadata:
  name: hotrod-frontend
spec:
  type: NodePort
  selector:
    app: hotrod-frontend
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30800

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod-frontend
  labels:
    app: hotrod-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod-frontend
  template:
    metadata:
      labels:
        app: hotrod-frontend
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "hotrod-customer:8081,hotrod-driver:8082,hotrod-route:8083"
    spec:
      containers:
      - name: hotrod-frontend
        image: "jaegertracing/example-hotrod:latest"
        imagePullPolicy: Always
        command: ["/go/bin/hotrod-linux"]
        args: ["frontend"]
        ports:
        - containerPort: 8080
        env:
          - name: JAEGER_AGENT_HOST
            value: "jaeger-agent"
          - name: JAEGER_AGENT_PORT
            value: "6831"
