---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  labels:
    product: aes
    app.kubernetes.io/component: ambassador-service
    cis.f5.com/as3-tenant: Kube
    cis.f5.com/as3-app: Ambassador
    cis.f5.com/as3-pool: gateway_pool
spec:
  type: NodePort
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    service: ambassador
