kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-ambassador
  namespace: default
  labels:
    f5type: virtual-server
    as3: 'true'
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.10.0",
        "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
        "label": "http",
        "remark": "A1 example",
        "Consul_SD": {
          "class": "Tenant",
          "Ambassador": {
            "class": "Application",
            "template": "https",
            "serviceMain": {
              "class": "Service_HTTPS",
              "virtualPort": 443,
              "clientTLS": {"bigip":"/Common/serverssl"},
              "serverTLS": {"bigip":"/Common/clientssl"},
              "virtualAddresses": [
                "10.3.0.4"
              ],
              "pool": "gateway_pool"
            },
            "gateway_pool": {
              "class": "Pool",
              "monitors": [
                "https"
              ],
              "members": [
                {
                  "servicePort": 443,
                  "serverAddresses": []
                }
              ]
            }
          }
        }
      }
    }
