---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traffic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
  labels:
    app: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
      annotations:
        prometheus.io/scrape: "false"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "frontend:80"
    spec:
      serviceAccountName: traffic
      containers:
      - name: traffic
        image: hashicorpdemoapp/traffic-simulation:v0.0.2
        env:
        - name: BASE_URI
          value: http://localhost
        - name: DURATION
          value: "24h"
        - name: SHOW_PROGRESS
          value: "false"
        - name: USERS
          value: "3"
