apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: graphql-ingress-gateway
spec:
  listeners:
    - port: 8080
      protocol: http
      services:
        - name: public-api
          hosts: ["*"]
